name: codecov
on: [push]
jobs:
  run-test:
    strategy:
      matrix:
        python-version: ['3.9', '3.8', '3.7', '3.6']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}WW
      - run: python3 -m pip install -r requirements.txt
      - run: coverage run -m pytest
      - run: coverage xml
      - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml