name: Test compiling imagetools.py using Nuitka
on: [push, pull_request]
jobs:
  test-compile:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install wheel and poetry
        run: pip install wheel poetry
      - name: Install packages from Poetry (including Nuitka)
        run: poetry install
      - name: Compile using Nuitka
        run: python3 -m nuitka imagetools.py --assume-yes-for-downloads --follow-imports