name: tests
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        architecture: ['x64']
        python-version: ['3.9', '3.8', '3.7', '3.6']
        include:
          - architecture: x86
            os: windows-latest
    name: test with Python ${{ matrix.python-version }} ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - run: cd $GITHUB_WORKSPACE
      - run: python3 -m pip install -r requirements.txt
      - run: python3 imagetools.py blur ./test_files/image.jpg
      - run: python3 imagetools.py sharpen ./test_files/image.jpg
      - run: python3 imagetools.py smooth ./test_files/image.jpg
      - run: python3 imagetools.py smooth+ ./test_files/image.jpg
      - run: python3 imagetools.py blur https://github.com/rahulrakida/imagetools/raw/main/test_files/image.jpg --url
      - run: python3 imagetools.py sharpen https://github.com/rahulrakida/imagetools/raw/main/test_files/image.jpg --url
      - run: python3 imagetools.py smooth https://github.com/rahulrakida/imagetools/raw/main/test_files/image.jpg --url
      - run: python3 imagetools.py smooth+ https://github.com/rahulrakida/imagetools/raw/main/test_files/image.jpg --url