name: tests
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        architecture: ['x64', 'x86']
        python-version: ['3.9']
    name: test with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - run: python3 -m pip install pillow
      - run: cd $GITHUB_WORKSPACE
      - run: python3 imagetools.py blur ./test_files/image.jpg
      - run: python3 imagetools.py sharpen ./test_files/image.jpg
      - run: python3 imagetools.py smooth ./test_files/image.jpg
      - run: python3 imagetools.py smooth+ ./test_files/image.jpg